param(
    [Parameter(Mandatory = $true)]
    [string]$AppDir,
    [Parameter(Mandatory = $true)]
    [string]$OutputDir,
    [Parameter(Mandatory = $true)]
    [string]$AppVersion,
    [Parameter(Mandatory = $true)]
    [string]$AppBuild,
    [string]$SetupIcon = "",
    [string]$AppIcon = "",
    [string]$SidebarPng = ""
)

$ErrorActionPreference = "Stop"

Write-Host "== Inno Setup Installer Packaging ==" -ForegroundColor Cyan
Write-Host "AppDir: $AppDir"
Write-Host "OutputDir: $OutputDir"
Write-Host "Version: $AppVersion (build $AppBuild)"

# Locate Inno Setup Compiler
$IsccPaths = @(
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles(x86)}\Inno Setup 5\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles}\Inno Setup 5\ISCC.exe",
    "${env:LOCALAPPDATA}\Programs\Inno Setup 6\ISCC.exe",
    "${env:LOCALAPPDATA}\Programs\Inno Setup 5\ISCC.exe"
)

$Iscc = $null
foreach ($path in $IsccPaths) {
    if (Test-Path $path) {
        $Iscc = $path
        break
    }
}

if ($Iscc -eq $null) {
    Write-Warning "Inno Setup Compiler (ISCC.exe) not found. Install Inno Setup from https://jrsoftware.org/isdl.php"
    Write-Warning "Falling back to jpackage MSI build..."

    # Try jpackage MSI as fallback
    $Jpackage = "${env:JAVA_HOME}\bin\jpackage.exe"
    if (Test-Path $Jpackage) {
        New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
        & $Jpackage --type msi --app-image $AppDir --dest $OutputDir --name Nuvio --app-version $AppVersion --vendor "Nuvio Media" --win-menu --win-shortcut
        Write-Host "MSI fallback created in $OutputDir" -ForegroundColor Green
    } else {
        Write-Warning "jpackage also not found. Skipping installer build."
    }
    return
}

# Create output directory
New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

# Create sidebar BMP from PNG if available
$SidebarBmp = Join-Path $OutputDir "installer-sidebar.bmp"
if (Test-Path $SidebarPng) {
    Add-Type -AssemblyName System.Drawing
    $img = [System.Drawing.Image]::FromFile($SidebarPng)
    $bmp = New-Object System.Drawing.Bitmap($img)
    $bmp.Save($SidebarBmp, [System.Drawing.Imaging.ImageFormat]::Bmp)
    $bmp.Dispose()
    $img.Dispose()
    Write-Host "Created sidebar BMP: $SidebarBmp" -ForegroundColor Green
}

# Create Inno Setup script
$IssContent = @"
; Nuvio Desktop Inno Setup Script
; Auto-generated by package-release-inno.ps1

#define MyAppName "Nuvio"
#define MyAppVersion "$AppVersion"
#define MyAppPublisher "Nuvio Media"
#define MyAppURL "https://nuvioapp.space"

[Setup]
AppId={{B8A7C8E3-2F5D-4A1E-9C8D-3F7E2A1B5C6D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputDir={#Param:OutputDir}
OutputBaseFilename=Nuvio-$AppVersion-Setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
SetupIconFile=$SetupIcon
UninstallDisplayIcon={app}\Nuvio.exe
"@

if (Test-Path $SidebarBmp) {
    $IssContent += @"

WizardSmallImageFile=$SidebarBmp
"@
}

$IssContent += @"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "$AppDir\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\Nuvio.exe"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\Nuvio.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Nuvio.exe"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup: Boolean;
begin
  Result := True;
end.
"@

$IssFile = Join-Path $OutputDir "Nuvio-$AppVersion.iss"
$IssContent | Out-File -FilePath $IssFile -Encoding ASCII
Write-Host "Created Inno script: $IssFile" -ForegroundColor Green

# Run ISCC
Write-Host "Running Inno Setup Compiler..." -ForegroundColor Green
& $Iscc $IssFile

if ($LASTEXITCODE -eq 0) {
    Write-Host "Inno Setup installer created successfully!" -ForegroundColor Green
    Get-ChildItem $OutputDir -Filter "*.exe" | Select-Object FullName, Length, LastWriteTime | Format-Table -AutoSize
} else {
    Write-Error "Inno Setup compilation failed with exit code $LASTEXITCODE"
    exit $LASTEXITCODE
}
